name: CI/CD for dockerized flask app
on:
    push:
      branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
        #Step1 Checkout the code
        - name: Checkout code
          uses: actions/checkout@v3
        #Step2: set the python environment
        - name: Set up the python
          uses: actions/checkout@v4
          with:
            python-version: "3.10"

        #Step3: Install Depemndencies
        - name: Install Dependencies
          run:
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        #Step4: Run the test cases
        - name: Run Test Case
          run:
            pytest
    
    ## Build and publish the docker images
    build-and-publish:
        needs: build-and-test
        runs-on: ubuntu-latest
        
        #steps to build and publish
        #Step 1: Check out the code
        steps:
        - name: Check out the code
          uses: actions/checkout@v3

        #Step2: set up the buildx
        - name: et up docker buildx
          uses: docker/setup-buildx-action@v2

        #Step3: Set login credentials of the git repo
        - name: Login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
        
        #Step4: buil;d and push docker image
        - name: Build and push docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{secrets.DOCKER_USERNAME}}/flasktest-app:latest

        - name: Image digest
          run: echo ${{steps.build-and-publish.outputs.digest}}

        




